// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiedPushService) DeepCopyInto(out *UnifiedPushService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiedPushService.
func (in *UnifiedPushService) DeepCopy() *UnifiedPushService {
	if in == nil {
		return nil
	}
	out := new(UnifiedPushService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiedPushService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiedPushServiceList) DeepCopyInto(out *UnifiedPushServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UnifiedPushService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiedPushServiceList.
func (in *UnifiedPushServiceList) DeepCopy() *UnifiedPushServiceList {
	if in == nil {
		return nil
	}
	out := new(UnifiedPushServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiedPushServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiedPushServiceSpec) DeepCopyInto(out *UnifiedPushServiceSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiedPushServiceSpec.
func (in *UnifiedPushServiceSpec) DeepCopy() *UnifiedPushServiceSpec {
	if in == nil {
		return nil
	}
	out := new(UnifiedPushServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiedPushServiceStatus) DeepCopyInto(out *UnifiedPushServiceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiedPushServiceStatus.
func (in *UnifiedPushServiceStatus) DeepCopy() *UnifiedPushServiceStatus {
	if in == nil {
		return nil
	}
	out := new(UnifiedPushServiceStatus)
	in.DeepCopyInto(out)
	return out
}
